name: Build-AssImp
on:
  create:

jobs:
  Run-assimp-go-macos:
    runs-on: macos-10.15
    steps:
      - name: Install golang 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Clone assimp-go
        run: git clone https://github.com/BhaumikTalwar/assimp-go
      - name: Copy dylib
        working-directory: assimp-go
        run: sudo mkdir -p /usr/local/lib && sudo cp asig/libs/libassimp_darwin_amd64.dylib /usr/local/lib/libassimp.5.dylib
      - name: Run assimp-go
        working-directory: assimp-go
        run: go run .
